config/routes.rb
Rails.application.routes.draw do
  
  resources :stocks
  resources :carriers
  resources :suscriptions
  resources :laundries do
    resources :products
  end
  resources :orders do
    resources :deliveries
  end
  
  # get 'home/index'

  resources :profiles, as: :users, only: [:update, :show]
  

  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  authenticated :user do
    root "home#index"
  end
  root "home#login"
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :laundry
  belongs_to :carrier
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
 
    
    case query_type
      when "drop"
        # Para consultas de retiro, filtrar por fechas mayores o iguales a AHORA.
        futuro_lejano = Time.now + 720.day
        @stocks = Stock.where(:laundry_id => laundry_id, :init_hour => ((Time.now)..futuro_lejano), :delivery_type => "drop")
        @carriers = Carrier.select("id, name")
      when "delivery"
         # Para consultas de entrega, sumar al producto los días de lavado y filtrar
         futuro_lejano = Time.now + 720.day
         if demora.to_i > 0
          minima_entrega = Time.now + demora.to_i.day
         else
          minima_entrega = Time.now + 35.day
         end
         @stocks = Stock.where(:laundry_id => laundry_id, init_hour: (minima_entrega ..futuro_lejano), :delivery_type => "delivery")
      else
        puts "Consulta con parámetro inválido"
        @stocks = Stock.all
    end
      

  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:laundry_id, :carrier_id, :init_hour, :ending_hour, :available, :remaining, :delivery_type)
    end
    def query_type
      params[:query_type].to_s
    end
    def laundry_id
      params[:laundry_id].to_i
    end
    def demora
      params[:demora]
    end
  end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :laundry_id %>
    <%= form.text_field :laundry_id %>
  </div>

  <div class="field">
    <%= form.label :carrier_id %>
    <%= form.text_field :carrier_id %>
  </div>

 

  <div class="field">
    <%= form.label :init_hour %>
    <%= form.text_field :init_hour %>
  </div>

  <div class="field">
    <%= form.label :ending_hour %>
    <%= form.text_field :ending_hour %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.text_field :available %>
  </div>

  <div class="field">
    <%= form.label :remaining %>
    <%= form.text_field :remaining %>
  </div>

  <div class="field">
    <%= form.label :delivery_type %>
    <%= form.text_field :delivery_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Laundry</th>
      <th>Carrier</th>

      <th>Hora inicio</th>
      <th>Hora fin</th>
      <th>Available</th>
      <th>Remaining</th>
      <th>Delivery type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.laundry %></td>
        <td><%= stock.carrier %></td>

        <td><%= stock.init_hour %></td>
        <td><%= stock.ending_hour %></td>
        <td><%= stock.available %></td>
        <td><%= stock.remaining %></td>
        <td><%= stock.delivery_type %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Laundry:</strong>
  <%= @stock.laundry %>
</p>

<p>
  <strong>Carrier:</strong>
  <%= @stock.carrier %>
</p>


<p>
  <strong>Init Hour:</strong>
  <%= @stock.init_hour %>
</p>

<p>
  <strong>Ending Hour:</strong>
  <%= @stock.ending_hour %>
</p>

<p>
  <strong>Available:</strong>
  <%= @stock.available %>
</p>

<p>
  <strong>Remaining:</strong>
  <%= @stock.remaining %>
</p>

<p>
  <strong>Delivery type:</strong>
  <%= @stock.delivery_type %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>