config/routes.rb
Rails.application.routes.draw do
  
  resources :stocks
  resources :carriers
  resources :suscriptions
  resources :laundries do
    resources :products
  end
  resources :orders do
    resources :deliveries
  end
  
  # get 'home/index'

  resources :profiles, as: :users, only: [:update, :show]
  

  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  authenticated :user do
    root "home#index"
  end
  root "home#login"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find(current_user.id)
    
    # Si alguno de los campos requeridos está vacío, pedir que complete el perfil.
    if @user.name == nil || @user.last_name == nil || @user.address == nil || @user.address_details == nil || @user.city == nil 
      redirect_to user_path(current_user)
    end
  end

  def login

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= if user_signed_in? then link_to('Cerrar sesión', destroy_user_session_path, method: :delete) else link_to('Iniciar sesión', new_user_session_path) end %>


<!--
<%= react_component("Profile", @user) %>

<p>
    <%= if user_signed_in? then link_to('Cerrar sesión', destroy_user_session_path, method: :delete) else link_to('Iniciar sesión', new_user_session_path) end %>
</p>
<% if (@incomplete_profile == true) %>
  <%= react_component("Profile", @user) %>
<% else %>
  <ul>
      
      <li><%= link_to('Lavanderías',laundries_path) %></li>
      <li><%= link_to('Suscripciones',suscriptions_path) %></li>
      <li><%= link_to('Pedidos',orders_path) %></li>
      <li><%= link_to('Cadetes',carriers_path) %></li>

  </ul>
<% end %>
Datos personales
<ul>
  <li>Email: <%= @user.email %></li>
  <li>Nombre: <%= @user.name %></li>
  <li>Apellido: <%= @user.last_name %></li>
  <li>Localidad: <%= @user.city %></li>
  <li>Dirección: <%= @user.address %></li>
  <li>Detalles de dirección: <%= @user.address_details %></li>
  <li>Puntaje por tus pedidos: <%= @user.score %></li>
 
</ul>
-->

app/views/home/login.html.erb
<div class="pantalla-completa">
    <div class="logo">
        <%= image_tag(asset_path('lafLessMargin'), height: '100px') %>
    </div>
    <div>
        <%= react_component("Registration") %>
    </div>
</div>