config/routes.rb
Rails.application.routes.draw do
  
  resources :stocks
  resources :carriers
  resources :suscriptions
  resources :laundries do
    resources :products
  end
  resources :orders do
    resources :deliveries
  end
  
  # get 'home/index'

  resources :profiles, as: :users, only: [:update, :show]
  

  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  authenticated :user do
    root "home#index"
  end
  root "home#login"
end

app/models/laundry.rb
class Laundry < ApplicationRecord
end

app/controllers/laundries_controller.rb
class LaundriesController < ApplicationController
  before_action :set_laundry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show
  require "rubygems"
  require "geokit"
  # antes de guardar que busque las coordenadas acá
  # https://maps.googleapis.com/maps/api/geocode/json?address=#{VARIABLECONLOQUEPUSOELUSER+,ROSARIO}&key=AIzaSyAP9BJ5wfeQ23i_gVQe0tbczeHcIcKNLWQ
  # o este otro que es open source
  # https://nominatim.openstreetmap.org/search?q=#{VARIABLECONLOQUEPUSOELUSER+,ROSARIO}&format=json
  
  # GET /laundries
  # GET /laundries.json
  def index
    @laundries = Laundry.all



    @dispLaundries = []
    @laundries.each do |laundry|
      unless laundry.coverage_area==nil
        cober = ActiveSupport::JSON.decode laundry.coverage_area
        points = []
        cober.each do |point|
          lat = point["lat"]
          lon = point["lon"]
          points << Geokit::LatLng.new(lat, lon)
        end
        coverage = Geokit::Polygon.new(points)
          client_location = Geokit::LatLng.new(params[:lat],params[:lon])
          if(coverage.contains? client_location)==true
            @dispLaundries << laundry.clone
          end
      
        
      end
    end
        
  end

  # GET /laundries/1
  # GET /laundries/1.json
  def show
  end

  # GET /laundries/new
  def new
    @laundry = Laundry.new
  end

  # GET /laundries/1/edit
  def edit
  end

  # POST /laundries
  # POST /laundries.json
  def create
    @laundry = Laundry.new(laundry_params)

    respond_to do |format|
      if @laundry.save
        format.html { redirect_to @laundry, notice: 'Laundry was successfully created.' }
        format.json { render :show, status: :created, location: @laundry }
      else
        format.html { render :new }
        format.json { render json: @laundry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laundries/1
  # PATCH/PUT /laundries/1.json
  def update
    respond_to do |format|
      if @laundry.update(laundry_params)
        format.html { redirect_to @laundry, notice: 'Laundry was successfully updated.' }
        format.json { render :show, status: :ok, location: @laundry }
      else
        format.html { render :edit }
        format.json { render json: @laundry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laundries/1
  # DELETE /laundries/1.json
  def destroy
    @laundry.destroy
    respond_to do |format|
      format.html { redirect_to laundries_url, notice: 'Laundry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laundry
      @laundry = Laundry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laundry_params
      params.require(:laundry).permit(:name, :score, :address, :address_details, :city, :logo, :cover, :coverage_area)
    end
end

app/helpers/laundries_helper.rb
module LaundriesHelper
end

app/views/laundries/_form.html.erb
<%= form_with(model: laundry, local: true) do |form| %>
  <% if laundry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laundry.errors.count, "error") %> prohibited this laundry from being saved:</h2>

      <ul>
      <% laundry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :laundry_name %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :laundry_score %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :laundry_address %>
  </div>

  <div class="field">
    <%= form.label :address_details %>
    <%= form.text_field :address_details, id: :laundry_address_details %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :laundry_city %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_field :logo, id: :laundry_logo %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.text_field :cover, id: :laundry_cover %>
  </div>

  <div class="field">
    <%= form.label :coverage_area %>
    <%= form.text_field :coverage_area, id: :laundry_coverage_area %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/laundries/edit.html.erb
<h1>Editing Laundry</h1>

<%= render 'form', laundry: @laundry %>

<%= link_to 'Show', @laundry %> |
<%= link_to 'Back', laundries_path %>

app/views/laundries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lavanderías</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Score</th>
      <th>Address</th>
      <th>Address details</th>
      <th>City</th>
      <th>Logo</th>
      <th>Cover</th>
      <th>Cobertura</th>
      <th>Disponible?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dispLaundries.each do |laundry| %>
      <tr>
        <td><%= laundry.name %></td>
        <td><%= laundry.score %></td>
        <td><%= laundry.address %></td>
        <td><%= laundry.address_details %></td>
        <td><%= laundry.city %></td>
        <td><%= laundry.logo %></td>
        <td><%= laundry.cover %></td>

        <td></td>
        <td></td>
        <td><%= link_to 'Show', laundry %></td>
        <td><%= link_to 'Edit', edit_laundry_path(laundry) %></td>
        <td><%= link_to 'Destroy', laundry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laundry', new_laundry_path %>
CASA: ?lat=-32.958850&lon=-60.648431

app/views/laundries/new.html.erb
<h1>New Laundry</h1>

<%= render 'form', laundry: @laundry %>

<%= link_to 'Back', laundries_path %>

app/views/laundries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @laundry.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @laundry.score %>
</p>

<p>
  <strong>Address:</strong>
  <%= @laundry.address %>
</p>

<p>
  <strong>Address details:</strong>
  <%= @laundry.address_details %>
</p>

<p>
  <strong>City:</strong>
  <%= @laundry.city %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @laundry.logo %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @laundry.cover %>
</p>

<p>
  <strong>Área de cobertura:</strong>
  <%= @laundry.coverage_area %>
</p>

<%= link_to 'Edit', edit_laundry_path(@laundry) %> |
<%= link_to 'Back', laundries_path %>