config/routes.rb
Rails.application.routes.draw do
  
  resources :stocks
  resources :carriers
  resources :suscriptions
  resources :laundries do
    resources :products
  end
  resources :orders do
    resources :deliveries
  end
  
  # get 'home/index'

  resources :profiles, as: :users, only: [:update, :show]
  

  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  authenticated :user do
    root "home#index"
  end
  root "home#login"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :laundry
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.where(laundry_id: params[:laundry_id])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :laundry_id, :description, :product_type, :picture, :score, :only_for_suscriptions)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :laundry_id %>
    <%= form.text_field :laundry_id, id: :product_laundry_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.number_field :type, id: :product_type %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :product_picture %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :product_score %>
  </div>

  <div class="field">
    <%= form.label :only_for_suscriptions %>
    <%= form.check_box :only_for_suscriptions, id: :product_only_for_suscriptions %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Laundry</th>
      <th>Description</th>
      <th>Type</th>
      <th>Picture</th>
      <th>Score</th>
      <th>Only for suscriptions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.laundry %></td>
        <td><%= product.description %></td>
        <td><%= product.product_type %></td>
        <td><%= product.picture %></td>
        <td><%= product.score %></td>
        <td><%= product.only_for_suscriptions %></td>
        <td><%= link_to 'Show', laundry_products_path(params[:laundry_id] , product.id) %></td>
        <td><%= link_to 'Edit', edit_laundry_product_path(params[:laundry_id] , product.id) %></td>
        <td><%= link_to 'Destroy', laundry_product_path(params[:laundry_id] , product.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_laundry_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Laundry:</strong>
  <%= @product.laundry %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.product_type %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @product.picture %>
</p>

<p>
  <strong>Score:</strong>
  <%= @product.score %>
</p>

<p>
  <strong>Only for suscriptions:</strong>
  <%= @product.only_for_suscriptions %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>